### ISSUE TITLE
Duplicate chromedriver package

### ISSUE THREAD

**Issue by dhoer** [yetanotherchris/Choco-chromedriver#1]
FYI, 
I had ask https://github.com/agabrys to fix issues with https://chocolatey.org/packages/selenium-chrome-driver a while back https://github.com/agabrys/chocolatey-packages/issues/17. So his driver should now work as expected. I don't know if you two could collaborate and maintain one driver and deprecate the other, but I thought I would ask.

**Comment by yetanotherchris** [comment]
I haven't contacted him, this one is fully automated and good for our use where we need to update to the latest Chromedriver on build servers pretty much the same day it comes.

This is more a problem with Chocolatey having no vetting of official packages - Chromedriver are welcome to pick up this project if you like, I would prefer to still have control over it though incase there is a delay in updating, as that can cause quite a few headaches.
