### ISSUE TITLE
Please can we have ChromeDriver 116?

### ISSUE THREAD

**Issue by timhunt** [yetanotherchris/Choco-chromedriver#10]
I use ChromeDriver through Chocolatey. Thank you for maintaining it.

My Chrome just updated to v116, so Selenium is now telling me "This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.97". It seems that the package has not been updated since 31 May 2023, which strangely seems to be just when it became a 'trusted' package -and it was well maintained before that. https://community.chocolatey.org/packages/chromedriver#versionhistory.

Wil you be able to update to the latest version? Is there anything we can do to help?

Thanks.

**Comment by timhunt** [comment]
Yes, I expect that is the issue. Sadly, I don't think I am in a position to fix it.

**Comment by studioj** [comment]
> > Yes, I expect that is the issue. Sadly, I don't think I am in a position to fix it.
> 
> I'll try to suggest a solution this evening with some python code in the GHA ... hope that would be ok for @yetanotherchris

was able to not use python although I must give credits to a certain popular generative language model

**Comment by studioj** [comment]
thx @yetanotherchris , fingers crossed for the first production run?

**Comment by yetanotherchris** [comment]
There's a problem with a missing `$disiredPlatform` so I'm going to hardcode to win32 for now, unless there's a better solution?

**Comment by yetanotherchris** [comment]
[v116](https://community.chocolatey.org/packages/chromedriver#versionhistory) is working it's way through Chocolatey right now

**Comment by studioj** [comment]
I dont know if the template needs to be able to support lower versions. I dont really know how the API works there.

**Comment by studioj** [comment]
now the chrome package still needs some updating its hash check fails

**Comment by yetanotherchris** [comment]
The template probably doesn't need to support that, as the ps file is zipped as part of the chocolately version. The $version parameter in the push powershell can also go at some point

**Comment by timhunt** [comment]
Thank you both for your work on this.
