### ISSUE TITLE
please update to version 79.0.3945.36

### ISSUE THREAD

**Issue by carct** [yetanotherchris/Choco-chromedriver#2]
please update to version 79.0.3945.36

tried to create a branch and push it so that i can raise a PR on your repo but didn't have permission to do it :(

**Comment by yetanotherchris** [comment]
You'll have to create a fork to do so, but I'll update - I've been waiting for it to stabilize but it looks fine now

**Comment by yetanotherchris** [comment]
https://chromedriver.storage.googleapis.com/LATEST_RELEASE looks like that's out of date
