### ISSUE TITLE
Please update chocolatey package to `105.0.5195.52`

### ISSUE THREAD

**Issue by bil0u** [yetanotherchris/Choco-chromedriver#7]
Hi !

Could it be possible to update the chromedriver version that is published on [Chocolatey packages](https://community.chocolatey.org/packages/chromedriver) to `105.0.5195.52` ?

It's current version is `104.0.5112.790`.

Also, maybe it could be possible to implement a chocolatey autopush job when a version changed by extending the exsting GitHub action ?

Happy to discuss if needed.

**Comment by hemdagem** [comment]
Updated to a new version.
